name: Convert event_data.xlsx to event_data.json

on:
  push:
    paths:
      - 'event_data.xlsx'
      - '.github/workflows/convert_event_data.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install pandas
        run: pip install pandas openpyxl
      - name: Convert Excel to JSON
        run: python convert_event_data.py
      - name: Commit and push event_data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add event_data.json
          git commit -m 'Auto convert event_data.xlsx to event_data.json [skip ci]' || echo "No changes"
          git push
