name: Generate and Publish Calendar

on:
  schedule:
    - cron: '0 0 * * *'   # 毎日9:00 JSTに実行（JST=UTC+9）
  workflow_dispatch:       # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install pandas
      - name: Generate HTML
        run: python generate_calendar_html.py
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Auto-generate index.html [skip ci]' || echo "No changes to commit"
          git push
